"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-05-17

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import bigrag.services.crypto
from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "embedding_cache",
        sa.Column("content_hash", sa.Text(), nullable=False),
        sa.Column("model_key", sa.Text(), nullable=False),
        sa.Column("vector", postgresql.BYTEA(), nullable=False),
        sa.Column("dimension", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_hit_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("content_hash", "model_key"),
    )
    op.create_index(
        "idx_embedding_cache_last_hit", "embedding_cache", ["last_hit_at"], unique=False
    )
    op.create_table(
        "embedding_presets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("provider", sa.Text(), nullable=False),
        sa.Column("model", sa.Text(), nullable=False),
        sa.Column("api_key", bigrag.services.crypto.EncryptedString(), nullable=False),
        sa.Column("base_url", sa.Text(), nullable=True),
        sa.Column("dimension", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index("idx_embedding_presets_name", "embedding_presets", ["name"], unique=False)
    op.create_table(
        "maintenance_locks",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=True),
        sa.Column("reason", sa.Text(), server_default="", nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_index(
        "idx_maintenance_locks_expires_at", "maintenance_locks", ["expires_at"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("display_name", sa.Text(), server_default="", nullable=False),
        sa.Column("role", sa.Text(), server_default="member", nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_index("idx_users_created_at_id", "users", ["created_at", "id"], unique=False)
    op.create_table(
        "api_keys",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("key_hash", sa.Text(), nullable=False),
        sa.Column("prefix", sa.Text(), nullable=False),
        sa.Column(
            "permissions",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key_hash"),
    )
    op.create_index("idx_api_keys_active", "api_keys", ["active"], unique=False)
    op.create_index(
        "idx_api_keys_created_at_id",
        "api_keys",
        [sa.literal_column("created_at DESC"), sa.literal_column("id DESC")],
        unique=False,
    )
    op.create_index("idx_api_keys_expires_at", "api_keys", ["expires_at"], unique=False)
    op.create_index("idx_api_keys_prefix", "api_keys", ["prefix"], unique=False)
    op.create_index("idx_api_keys_user_id", "api_keys", ["user_id"], unique=False)
    op.create_table(
        "collections",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), server_default="", nullable=False),
        sa.Column("embedding_provider", sa.Text(), server_default="openai", nullable=False),
        sa.Column(
            "embedding_model", sa.Text(), server_default="text-embedding-3-small", nullable=False
        ),
        sa.Column("embedding_api_key", bigrag.services.crypto.EncryptedString(), nullable=True),
        sa.Column("embedding_base_url", sa.Text(), nullable=True),
        sa.Column("embedding_preset_id", sa.Uuid(), nullable=True),
        sa.Column("dimension", sa.Integer(), server_default=sa.text("1536"), nullable=False),
        sa.Column("chunk_size", sa.Integer(), server_default=sa.text("512"), nullable=False),
        sa.Column("chunk_overlap", sa.Integer(), server_default=sa.text("50"), nullable=False),
        sa.Column("chunk_strategy", sa.Text(), server_default="paragraph", nullable=False),
        sa.Column("document_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("default_top_k", sa.Integer(), server_default=sa.text("10"), nullable=False),
        sa.Column("default_min_score", sa.Double(), nullable=True),
        sa.Column("default_search_mode", sa.Text(), server_default="semantic", nullable=False),
        sa.Column(
            "reranking_enabled", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("reranking_model", sa.Text(), server_default="rerank-v3.5", nullable=False),
        sa.Column("reranking_api_key", bigrag.services.crypto.EncryptedString(), nullable=True),
        sa.Column(
            "multimodal_enabled", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "multimodal_enrichment_enabled",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column("tenant_field", sa.Text(), nullable=True),
        sa.Column("metadata_schema", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["embedding_preset_id"], ["embedding_presets.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(
        "idx_collections_created_at_id",
        "collections",
        [sa.literal_column("created_at DESC"), sa.literal_column("id DESC")],
        unique=False,
    )
    op.create_index("idx_collections_name", "collections", ["name"], unique=False)
    op.create_table(
        "instance_settings",
        sa.Column("key", sa.Text(), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("secret_value", bigrag.services.crypto.EncryptedString(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["updated_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_index("idx_sessions_expires_at", "sessions", ["expires_at"], unique=False)
    op.create_index("idx_sessions_user_id", "sessions", ["user_id"], unique=False)
    op.create_table(
        "user_preferences",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "data",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "webhooks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("secret", bigrag.services.crypto.EncryptedString(), nullable=False),
        sa.Column("events", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("collections", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column("active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_webhooks_active", "webhooks", ["active"], unique=False)
    op.create_index(
        "idx_webhooks_created_at_id",
        "webhooks",
        [sa.literal_column("created_at DESC"), sa.literal_column("id DESC")],
        unique=False,
    )
    op.create_index("idx_webhooks_created_by", "webhooks", ["created_by"], unique=False)
    op.create_table(
        "access_log",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("actor_email", sa.Text(), nullable=True),
        sa.Column("api_key_id", sa.Uuid(), nullable=True),
        sa.Column("api_key_name", sa.Text(), nullable=True),
        sa.Column("auth_method", sa.Text(), nullable=True),
        sa.Column("action", sa.Text(), server_default="http.request", nullable=False),
        sa.Column("resource_type", sa.Text(), server_default="http", nullable=False),
        sa.Column("resource_id", sa.Text(), nullable=True),
        sa.Column("collection_name", sa.Text(), nullable=True),
        sa.Column("method", sa.Text(), nullable=False),
        sa.Column("path", sa.Text(), nullable=False),
        sa.Column("route", sa.Text(), nullable=True),
        sa.Column("status_code", sa.Integer(), nullable=False),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("latency_ms", sa.Double(), nullable=False),
        sa.Column("request_id", sa.Text(), nullable=True),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("ip", sa.Text(), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["actor_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["api_key_id"], ["api_keys.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_access_log_action", "access_log", ["action"], unique=False)
    op.create_index(
        "idx_access_log_action_created_at",
        "access_log",
        ["action", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index("idx_access_log_actor", "access_log", ["actor_id"], unique=False)
    op.create_index(
        "idx_access_log_actor_created_at",
        "access_log",
        ["actor_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index("idx_access_log_api_key_id", "access_log", ["api_key_id"], unique=False)
    op.create_index("idx_access_log_collection", "access_log", ["collection_name"], unique=False)
    op.create_index(
        "idx_access_log_collection_created_at",
        "access_log",
        ["collection_name", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        "idx_access_log_created_at",
        "access_log",
        [sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index("idx_access_log_status", "access_log", ["status_code"], unique=False)
    op.create_index("idx_access_log_success", "access_log", ["success"], unique=False)
    op.create_table(
        "audit_log",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("actor_email", sa.Text(), nullable=True),
        sa.Column("api_key_id", sa.Uuid(), nullable=True),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column("resource_type", sa.Text(), nullable=False),
        sa.Column("resource_id", sa.Text(), nullable=True),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("ip", sa.Text(), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["actor_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["api_key_id"], ["api_keys.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_audit_action", "audit_log", ["action"], unique=False)
    op.create_index("idx_audit_actor", "audit_log", ["actor_id"], unique=False)
    op.create_index("idx_audit_api_key_id", "audit_log", ["api_key_id"], unique=False)
    op.create_index(
        "idx_audit_created_at", "audit_log", [sa.literal_column("created_at DESC")], unique=False
    )
    op.create_table(
        "chat_question_suggestions",
        sa.Column("collection_id", sa.Uuid(), nullable=False),
        sa.Column(
            "questions",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("model", sa.Text(), nullable=True),
        sa.Column("generated_by", sa.Uuid(), nullable=True),
        sa.Column(
            "generated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["collection_id"], ["collections.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["generated_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("collection_id"),
    )
    op.create_table(
        "connector_sources",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.Text(), nullable=False),
        sa.Column("collection_id", sa.Uuid(), nullable=False),
        sa.Column("collection_name", sa.Text(), nullable=False),
        sa.Column("tenant_id", sa.Text(), nullable=True),
        sa.Column("root_id", sa.Text(), nullable=False),
        sa.Column("root_name", sa.Text(), nullable=False),
        sa.Column("source_type", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default="idle", nullable=False),
        sa.Column("schedule_enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "sync_interval_hours", sa.Integer(), server_default=sa.text("24"), nullable=False
        ),
        sa.Column("last_sync_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_sync_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("provider <> ''", name="connector_sources_provider_check"),
        sa.CheckConstraint("source_type IN ('prefix')", name="connector_sources_source_type_check"),
        sa.CheckConstraint(
            "status IN ('idle', 'syncing', 'error')",
            name="connector_sources_status_check",
        ),
        sa.ForeignKeyConstraint(["collection_id"], ["collections.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "provider",
            "collection_id",
            "root_id",
            name="uq_connector_sources_provider_collection_root",
        ),
    )
    op.create_index(
        "idx_connector_sources_collection_id", "connector_sources", ["collection_id"], unique=False
    )
    op.create_index(
        "idx_connector_sources_next_sync", "connector_sources", ["next_sync_at"], unique=False
    )
    op.create_table(
        "connector_source_credentials",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("access_key_id", bigrag.services.crypto.EncryptedString(), nullable=False),
        sa.Column("secret_access_key", bigrag.services.crypto.EncryptedString(), nullable=False),
        sa.Column("session_token", bigrag.services.crypto.EncryptedString(), nullable=True),
        sa.Column("region", sa.Text(), server_default="us-east-1", nullable=False),
        sa.Column("endpoint_url", sa.Text(), nullable=True),
        sa.Column(
            "force_path_style", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["source_id"], ["connector_sources.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_id"),
    )
    op.create_index(
        "idx_connector_source_credentials_source_id",
        "connector_source_credentials",
        ["source_id"],
        unique=False,
    )
    op.create_table(
        "documents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("collection_id", sa.Uuid(), nullable=False),
        sa.Column("filename", sa.Text(), nullable=False),
        sa.Column("file_type", sa.Text(), server_default="", nullable=False),
        sa.Column("file_size", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("file_path", sa.Text(), server_default="", nullable=False),
        sa.Column("chunk_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("token_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "multimodal_element_count",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("content_hash", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), server_default="pending", nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["collection_id"], ["collections.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_documents_collection_created_at",
        "documents",
        ["collection_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        "idx_documents_collection_hash",
        "documents",
        ["collection_id", "content_hash"],
        unique=False,
    )
    op.create_index("idx_documents_collection_id", "documents", ["collection_id"], unique=False)
    op.create_index(
        "idx_documents_collection_status_created_at",
        "documents",
        ["collection_id", "status", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index("idx_documents_created_at", "documents", ["created_at"], unique=False)
    op.create_index("idx_documents_status", "documents", ["status"], unique=False)
    op.create_table(
        "document_elements",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("collection_id", sa.Uuid(), nullable=False),
        sa.Column("element_index", sa.Integer(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("text", sa.Text(), server_default="", nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("caption", sa.Text(), nullable=True),
        sa.Column("asset_path", sa.Text(), nullable=True),
        sa.Column("page_no", sa.Integer(), nullable=True),
        sa.Column("bbox", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("char_start", sa.Integer(), nullable=True),
        sa.Column("char_end", sa.Integer(), nullable=True),
        sa.Column("surrounding_context", sa.Text(), nullable=True),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "enrichment_status",
            sa.Text(),
            server_default="not_requested",
            nullable=False,
        ),
        sa.Column("enrichment_error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('text', 'heading', 'table', 'image', 'equation', 'unknown')",
            name="document_elements_kind_check",
        ),
        sa.CheckConstraint(
            "enrichment_status IN ('not_requested', 'pending', 'ready', 'failed')",
            name="document_elements_enrichment_status_check",
        ),
        sa.ForeignKeyConstraint(["collection_id"], ["collections.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document_id", "element_index", name="uq_document_elements_index"),
    )
    op.create_index(
        "idx_document_elements_collection_kind",
        "document_elements",
        ["collection_id", "kind"],
        unique=False,
    )
    op.create_index(
        "idx_document_elements_document",
        "document_elements",
        ["document_id", "element_index"],
        unique=False,
    )
    op.create_index(
        "idx_document_elements_enrichment",
        "document_elements",
        ["enrichment_status"],
        unique=False,
    )
    op.create_table(
        "query_log",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("collection_id", sa.Uuid(), nullable=True),
        sa.Column("collection_name", sa.Text(), nullable=False),
        sa.Column("query", sa.Text(), nullable=False),
        sa.Column("top_k", sa.Integer(), nullable=False),
        sa.Column("result_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("avg_score", sa.Double(), nullable=True),
        sa.Column("latency_ms", sa.Double(), nullable=True),
        sa.Column("search_mode", sa.Text(), server_default="semantic", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["collection_id"], ["collections.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_query_log_collection", "query_log", ["collection_name"], unique=False)
    op.create_index("idx_query_log_collection_id", "query_log", ["collection_id"], unique=False)
    op.create_index("idx_query_log_created_at", "query_log", ["created_at"], unique=False)
    op.create_table(
        "upload_sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("collection_id", sa.Uuid(), nullable=False),
        sa.Column("collection_name", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default="preparing", nullable=False),
        sa.Column("total_files", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("total_bytes", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("uploaded_files", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("queued_files", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("completed_files", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("failed_files", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("canceled_files", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('preparing', 'uploading', 'ingesting', 'complete', 'failed', 'canceled')",
            name="upload_sessions_status_check",
        ),
        sa.ForeignKeyConstraint(["collection_id"], ["collections.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_upload_sessions_collection_created",
        "upload_sessions",
        ["collection_id", "created_at"],
        unique=False,
    )
    op.create_index("idx_upload_sessions_status", "upload_sessions", ["status"], unique=False)
    op.create_table(
        "webhook_deliveries",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("webhook_id", sa.Uuid(), nullable=False),
        sa.Column("event", sa.Text(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.Text(), server_default="pending", nullable=False),
        sa.Column("attempts", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("last_status_code", sa.Integer(), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("next_retry_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["webhook_id"], ["webhooks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_webhook_deliveries_pending_retry",
        "webhook_deliveries",
        ["status", "next_retry_at", "created_at"],
        unique=False,
    )
    op.create_index("idx_webhook_deliveries_status", "webhook_deliveries", ["status"], unique=False)
    op.create_index(
        "idx_webhook_deliveries_webhook_id", "webhook_deliveries", ["webhook_id"], unique=False
    )
    op.create_table(
        "connector_documents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("remote_id", sa.Text(), nullable=False),
        sa.Column("remote_name", sa.Text(), nullable=False),
        sa.Column("remote_mime_type", sa.Text(), server_default="", nullable=False),
        sa.Column("remote_checksum", sa.Text(), nullable=True),
        sa.Column("remote_version", sa.Text(), nullable=True),
        sa.Column("remote_modified_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("content_hash", sa.Text(), nullable=True),
        sa.Column("web_url", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), server_default="active", nullable=False),
        sa.Column("last_seen_job_id", sa.Uuid(), nullable=True),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["source_id"], ["connector_sources.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_id", "remote_id", name="uq_connector_documents_source_remote"),
    )
    op.create_index(
        "idx_connector_documents_document_id", "connector_documents", ["document_id"], unique=False
    )
    op.create_index(
        "idx_connector_documents_source_remote",
        "connector_documents",
        ["source_id", "remote_id"],
        unique=False,
    )
    op.create_index(
        "idx_connector_documents_source_last_seen",
        "connector_documents",
        ["source_id", "last_seen_job_id"],
        unique=False,
    )
    op.create_table(
        "connector_sync_jobs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.Text(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=True),
        sa.Column("trigger", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default="pending", nullable=False),
        sa.Column("started_by", sa.Uuid(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("total_found", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("total_created", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("total_updated", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("total_skipped", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("total_deleted", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("total_failed", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "details",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("provider <> ''", name="connector_sync_jobs_provider_check"),
        sa.CheckConstraint(
            "status IN ('pending', 'running', 'complete', 'failed')",
            name="connector_sync_jobs_status_check",
        ),
        sa.CheckConstraint(
            "trigger IN ('initial', 'manual', 'scheduled')",
            name="connector_sync_jobs_trigger_check",
        ),
        sa.ForeignKeyConstraint(["source_id"], ["connector_sources.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["started_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_connector_sync_jobs_source_created",
        "connector_sync_jobs",
        ["source_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "idx_connector_sync_jobs_status", "connector_sync_jobs", ["status"], unique=False
    )
    op.create_table(
        "upload_session_items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("client_item_id", sa.Text(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=True),
        sa.Column("filename", sa.Text(), nullable=False),
        sa.Column("file_type", sa.Text(), server_default="", nullable=False),
        sa.Column("file_size", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("content_hash", sa.Text(), nullable=True),
        sa.Column("storage_key", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), server_default="queued", nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('queued', 'complete', 'failed', 'canceled')",
            name="upload_session_items_status_check",
        ),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["session_id"], ["upload_sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id", "client_item_id", name="uq_upload_items_session_client"),
    )
    op.create_index(
        "idx_upload_session_items_document", "upload_session_items", ["document_id"], unique=False
    )
    op.create_index(
        "idx_upload_session_items_session", "upload_session_items", ["session_id"], unique=False
    )
    op.create_index(
        "idx_upload_session_items_status", "upload_session_items", ["status"], unique=False
    )
    # ### end Alembic commands ###

    op.execute(
        """
        CREATE OR REPLACE FUNCTION audit_log_block_content_modifications()
        RETURNS trigger AS $$
        BEGIN
            IF OLD.action IS DISTINCT FROM NEW.action
               OR OLD.resource_type IS DISTINCT FROM NEW.resource_type
               OR OLD.resource_id IS DISTINCT FROM NEW.resource_id
               OR OLD.metadata IS DISTINCT FROM NEW.metadata
               OR OLD.created_at IS DISTINCT FROM NEW.created_at
               OR OLD.actor_email IS DISTINCT FROM NEW.actor_email
               OR OLD.ip IS DISTINCT FROM NEW.ip
               OR OLD.user_agent IS DISTINCT FROM NEW.user_agent THEN
                RAISE EXCEPTION 'audit_log content is immutable';
            END IF;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE OR REPLACE FUNCTION audit_log_block_delete()
        RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION 'audit_log rows cannot be deleted';
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute("DROP TRIGGER IF EXISTS audit_log_no_content_update ON audit_log")
    op.execute(
        """
        CREATE TRIGGER audit_log_no_content_update
        BEFORE UPDATE ON audit_log
        FOR EACH ROW EXECUTE FUNCTION audit_log_block_content_modifications();
        """
    )
    op.execute("DROP TRIGGER IF EXISTS audit_log_no_delete ON audit_log")
    op.execute(
        """
        CREATE TRIGGER audit_log_no_delete
        BEFORE DELETE ON audit_log
        FOR EACH ROW EXECUTE FUNCTION audit_log_block_delete();
        """
    )

    op.drop_index("idx_access_log_actor", table_name="access_log")
    op.drop_index("idx_access_log_action", table_name="access_log")
    op.drop_index("idx_access_log_collection", table_name="access_log")
    op.drop_index("idx_documents_collection_id", table_name="documents")

    op.create_check_constraint(
        "users_role_check",
        "users",
        "role IN ('admin', 'member')",
    )
    op.create_check_constraint(
        "documents_status_check",
        "documents",
        "status IN ('pending', 'processing', 'ready', 'failed')",
    )
    op.create_check_constraint(
        "webhook_deliveries_status_check",
        "webhook_deliveries",
        "status IN ('pending', 'delivered', 'failed')",
    )
    op.create_check_constraint(
        "embedding_presets_provider_check",
        "embedding_presets",
        "provider IN ('openai', 'openai_compatible', 'cohere', 'voyage')",
    )

    op.drop_index("idx_documents_collection_hash", table_name="documents")
    op.create_index(
        "idx_documents_collection_hash",
        "documents",
        ["collection_id", "content_hash"],
        unique=False,
        postgresql_where=sa.text("content_hash IS NOT NULL"),
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS audit_log_no_delete ON audit_log")
    op.execute("DROP TRIGGER IF EXISTS audit_log_no_content_update ON audit_log")
    op.execute("DROP FUNCTION IF EXISTS audit_log_block_delete()")
    op.execute("DROP FUNCTION IF EXISTS audit_log_block_content_modifications()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_upload_session_items_status", table_name="upload_session_items")
    op.drop_index("idx_upload_session_items_session", table_name="upload_session_items")
    op.drop_index("idx_upload_session_items_document", table_name="upload_session_items")
    op.drop_table("upload_session_items")
    op.drop_index("idx_connector_sync_jobs_status", table_name="connector_sync_jobs")
    op.drop_index("idx_connector_sync_jobs_source_created", table_name="connector_sync_jobs")
    op.drop_table("connector_sync_jobs")
    op.drop_index("idx_connector_documents_source_last_seen", table_name="connector_documents")
    op.drop_index("idx_connector_documents_source_remote", table_name="connector_documents")
    op.drop_index("idx_connector_documents_document_id", table_name="connector_documents")
    op.drop_table("connector_documents")
    op.drop_index("idx_webhook_deliveries_webhook_id", table_name="webhook_deliveries")
    op.drop_index("idx_webhook_deliveries_status", table_name="webhook_deliveries")
    op.drop_index("idx_webhook_deliveries_pending_retry", table_name="webhook_deliveries")
    op.drop_table("webhook_deliveries")
    op.drop_index("idx_upload_sessions_status", table_name="upload_sessions")
    op.drop_index("idx_upload_sessions_collection_created", table_name="upload_sessions")
    op.drop_table("upload_sessions")
    op.drop_index("idx_query_log_created_at", table_name="query_log")
    op.drop_index("idx_query_log_collection_id", table_name="query_log")
    op.drop_index("idx_query_log_collection", table_name="query_log")
    op.drop_table("query_log")
    op.drop_index("idx_document_elements_enrichment", table_name="document_elements")
    op.drop_index("idx_document_elements_document", table_name="document_elements")
    op.drop_index("idx_document_elements_collection_kind", table_name="document_elements")
    op.drop_table("document_elements")
    op.drop_index("idx_documents_status", table_name="documents")
    op.drop_index("idx_documents_created_at", table_name="documents")
    op.drop_index("idx_documents_collection_status_created_at", table_name="documents")
    op.drop_index("idx_documents_collection_id", table_name="documents")
    op.drop_index("idx_documents_collection_hash", table_name="documents")
    op.drop_index("idx_documents_collection_created_at", table_name="documents")
    op.drop_table("documents")
    op.drop_index(
        "idx_connector_source_credentials_source_id",
        table_name="connector_source_credentials",
    )
    op.drop_table("connector_source_credentials")
    op.drop_index("idx_connector_sources_next_sync", table_name="connector_sources")
    op.drop_index("idx_connector_sources_collection_id", table_name="connector_sources")
    op.drop_table("connector_sources")
    op.drop_table("chat_question_suggestions")
    op.drop_index("idx_audit_created_at", table_name="audit_log")
    op.drop_index("idx_audit_api_key_id", table_name="audit_log")
    op.drop_index("idx_audit_actor", table_name="audit_log")
    op.drop_index("idx_audit_action", table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_index("idx_access_log_success", table_name="access_log")
    op.drop_index("idx_access_log_status", table_name="access_log")
    op.drop_index("idx_access_log_created_at", table_name="access_log")
    op.drop_index("idx_access_log_collection_created_at", table_name="access_log")
    op.drop_index("idx_access_log_collection", table_name="access_log")
    op.drop_index("idx_access_log_api_key_id", table_name="access_log")
    op.drop_index("idx_access_log_actor_created_at", table_name="access_log")
    op.drop_index("idx_access_log_actor", table_name="access_log")
    op.drop_index("idx_access_log_action_created_at", table_name="access_log")
    op.drop_index("idx_access_log_action", table_name="access_log")
    op.drop_table("access_log")
    op.drop_index("idx_webhooks_created_by", table_name="webhooks")
    op.drop_index("idx_webhooks_created_at_id", table_name="webhooks")
    op.drop_index("idx_webhooks_active", table_name="webhooks")
    op.drop_table("webhooks")
    op.drop_table("user_preferences")
    op.drop_index("idx_sessions_user_id", table_name="sessions")
    op.drop_index("idx_sessions_expires_at", table_name="sessions")
    op.drop_table("sessions")
    op.drop_table("instance_settings")
    op.drop_index("idx_collections_name", table_name="collections")
    op.drop_index("idx_collections_created_at_id", table_name="collections")
    op.drop_table("collections")
    op.drop_index("idx_api_keys_user_id", table_name="api_keys")
    op.drop_index("idx_api_keys_prefix", table_name="api_keys")
    op.drop_index("idx_api_keys_expires_at", table_name="api_keys")
    op.drop_index("idx_api_keys_created_at_id", table_name="api_keys")
    op.drop_index("idx_api_keys_active", table_name="api_keys")
    op.drop_table("api_keys")
    op.drop_index("idx_users_created_at_id", table_name="users")
    op.drop_table("users")
    op.drop_index("idx_maintenance_locks_expires_at", table_name="maintenance_locks")
    op.drop_table("maintenance_locks")
    op.drop_index("idx_embedding_presets_name", table_name="embedding_presets")
    op.drop_table("embedding_presets")
    op.drop_index("idx_embedding_cache_last_hit", table_name="embedding_cache")
    op.drop_table("embedding_cache")
    # ### end Alembic commands ###
