from __future__ import annotations

from bigrag.services.runtime_setting_specs._spec import SettingSpec

INGESTION_SPECS: tuple[SettingSpec, ...] = (
    SettingSpec(
        key="max_upload_size_mb",
        group="ingestion",
        label="Max upload size",
        kind="int",
        default=64,
        description="Maximum size for a single uploaded document in MB.",
        min=1,
        max=1024,
    ),
    SettingSpec(
        key="max_batch_upload_size_mb",
        group="ingestion",
        label="Max batch upload size",
        kind="int",
        default=128,
        description="Maximum aggregate size for a batch upload in MB.",
        min=1,
        max=102400,
    ),
    SettingSpec(
        key="max_upload_session_files",
        group="ingestion",
        label="Max upload session files",
        kind="int",
        default=10000,
        description="Maximum files accepted by a resumable upload session.",
        min=1,
        max=100000,
    ),
    SettingSpec(
        key="max_upload_session_size_mb",
        group="ingestion",
        label="Max upload session size",
        kind="int",
        default=102400,
        description="Maximum aggregate size for a resumable upload session in MB.",
        min=1,
        max=1048576,
    ),
    SettingSpec(
        key="conversion_pdf_ocr_enabled",
        group="ingestion",
        label="PDF OCR",
        kind="bool",
        default=True,
        description="OCR scanned PDFs when no embedded text is found.",
    ),
    SettingSpec(
        key="conversion_timeout",
        group="ingestion",
        label="Conversion timeout",
        kind="int",
        default=300,
        description="Docling conversion timeout in seconds.",
        min=10,
        max=86400,
    ),
    SettingSpec(
        key="ingestion_batch_size",
        group="ingestion",
        label="Ingestion batch size",
        kind="int",
        default=512,
        description=(
            "Vector insert batch size for ingestion workers; "
            "runs parallel via embedding_concurrency."
        ),
        min=1,
        max=4096,
    ),
    SettingSpec(
        key="max_vector_upsert_count",
        group="ingestion",
        label="Max vector upsert count",
        kind="int",
        default=1000,
        description="Maximum vectors accepted by one raw vector upsert request.",
        min=1,
        max=1000000,
    ),
    SettingSpec(
        key="max_vector_delete_count",
        group="ingestion",
        label="Max vector delete count",
        kind="int",
        default=10000,
        description="Maximum vector IDs accepted by one raw vector delete request.",
        min=1,
        max=1000000,
    ),
    SettingSpec(
        key="max_vector_text_chars",
        group="ingestion",
        label="Max vector text chars",
        kind="int",
        default=100000,
        description="Maximum text characters accepted on one raw vector entry.",
        min=0,
        max=10000000,
    ),
    SettingSpec(
        key="max_vector_metadata_bytes",
        group="ingestion",
        label="Max vector metadata bytes",
        kind="int",
        default=65536,
        description="Maximum JSON metadata bytes accepted on one raw vector entry.",
        min=0,
        max=10485760,
    ),
)
