from __future__ import annotations

from bigrag.services.runtime_setting_specs._spec import SettingSpec

SECURITY_SPECS: tuple[SettingSpec, ...] = (
    SettingSpec(
        key="cors_origins",
        group="security",
        label="CORS origins",
        kind="string_list",
        default=[],
        description="Browser origins allowed to call the API with credentials.",
    ),
    SettingSpec(
        key="trusted_proxies",
        group="security",
        label="Trusted proxies",
        kind="string_list",
        default=[],
        description="CIDR ranges trusted for forwarded client IP headers.",
    ),
    SettingSpec(
        key="session_cookie_secure",
        group="security",
        label="Secure session cookie",
        kind="bool",
        default=False,
        description="Send the admin session cookie only over HTTPS.",
    ),
    SettingSpec(
        key="session_cookie_samesite",
        group="security",
        label="Session SameSite",
        kind="select",
        default="lax",
        description="Browser SameSite policy for admin sessions.",
        options=("lax", "strict", "none"),
    ),
    SettingSpec(
        key="session_cookie_domain",
        group="security",
        label="Session cookie domain",
        kind="string",
        default=None,
        description="Optional cookie domain for split frontend and API deployments.",
    ),
    SettingSpec(
        key="allowed_embedding_base_urls",
        group="security",
        label="Allowed embedding base URLs",
        kind="string_list",
        default=[],
        description="Explicit external embedding endpoints allowed by outbound URL policy.",
    ),
    SettingSpec(
        key="allow_private_embedding_base_urls",
        group="security",
        label="Private embedding URLs",
        kind="bool",
        default=False,
        description="Allow embedding endpoints on private networks.",
    ),
    SettingSpec(
        key="allowed_chat_base_urls",
        group="security",
        label="Allowed chat base URLs",
        kind="string_list",
        default=[],
        description="Explicit external chat endpoints allowed by outbound URL policy.",
    ),
    SettingSpec(
        key="allow_private_chat_base_urls",
        group="security",
        label="Private chat URLs",
        kind="bool",
        default=False,
        description="Allow chat endpoints on private networks.",
    ),
    SettingSpec(
        key="allow_local_webhooks",
        group="security",
        label="Local webhook URLs",
        kind="bool",
        default=False,
        description="Allow webhook delivery to loopback URLs.",
    ),
    SettingSpec(
        key="embedding_cache_mode",
        group="security",
        label="Embedding cache mode",
        kind="select",
        default="encrypted",
        description="Persistent chunk embedding cache behavior.",
        options=("encrypted", "disabled"),
    ),
)
