// @ts-nocheck

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as AuthRouteImport } from "./routes/_auth";
import { Route as DashboardRouteImport } from "./routes/_dashboard";
import { Route as OnboardingRouteImport } from "./routes/onboarding";
import { Route as AuthLoginRouteImport } from "./routes/_auth.login";
import { Route as AuthSetupRouteImport } from "./routes/_auth.setup";
import { Route as DashboardAccessLogsRouteImport } from "./routes/_dashboard.access-logs";
import { Route as DashboardApiKeysRouteImport } from "./routes/_dashboard.api-keys";
import { Route as DashboardAuditRouteImport } from "./routes/_dashboard.audit";
import { Route as DashboardChatRouteImport } from "./routes/_dashboard.chat";
import { Route as DashboardConnectorsRouteImport } from "./routes/_dashboard.connectors";
import { Route as DashboardEvalsRouteImport } from "./routes/_dashboard.evals";
import { Route as DashboardMcpRouteImport } from "./routes/_dashboard.mcp";
import { Route as DashboardModelsRouteImport } from "./routes/_dashboard.models";
import { Route as DashboardOverviewRouteImport } from "./routes/_dashboard.overview";
import { Route as DashboardSettingsRouteImport } from "./routes/_dashboard.settings";
import { Route as DashboardUsageRouteImport } from "./routes/_dashboard.usage";
import { Route as DashboardWebhooksRouteImport } from "./routes/_dashboard.webhooks";
import { Route as DashboardCollectionsIndexRouteImport } from "./routes/_dashboard.collections.index";
import { Route as DashboardCollectionsNameRouteImport } from "./routes/_dashboard.collections.$name";
import { Route as DashboardCollectionsNameIndexRouteImport } from "./routes/_dashboard.collections.$name.index";
import { Route as DashboardCollectionsNameConnectorsRouteImport } from "./routes/_dashboard.collections.$name.connectors";
import { Route as DashboardCollectionsNameSearchRouteImport } from "./routes/_dashboard.collections.$name.search";
import { Route as DashboardCollectionsNameSettingsRouteImport } from "./routes/_dashboard.collections.$name.settings";
import { Route as DashboardCollectionsNameConnectorsIndexRouteImport } from "./routes/_dashboard.collections.$name.connectors.index";
import { Route as DashboardCollectionsNameConnectorsS3RouteImport } from "./routes/_dashboard.collections.$name.connectors.s3";
import { Route as DashboardCollectionsNameDocumentsIndexRouteImport } from "./routes/_dashboard.collections.$name.documents.index";
import { Route as DashboardCollectionsNameDocumentsDocIdRouteImport } from "./routes/_dashboard.collections.$name.documents.$docId";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthRoute = AuthRouteImport.update({
  id: "/_auth",
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardRoute = DashboardRouteImport.update({
  id: "/_dashboard",
  getParentRoute: () => rootRouteImport,
} as any);
const OnboardingRoute = OnboardingRouteImport.update({
  id: "/onboarding",
  path: "/onboarding",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => AuthRoute,
} as any);
const AuthSetupRoute = AuthSetupRouteImport.update({
  id: "/setup",
  path: "/setup",
  getParentRoute: () => AuthRoute,
} as any);
const DashboardAccessLogsRoute = DashboardAccessLogsRouteImport.update({
  id: "/access-logs",
  path: "/access-logs",
  getParentRoute: () => DashboardRoute,
} as any);
const DashboardApiKeysRoute = DashboardApiKeysRouteImport.update({
  id: "/api-keys",
  path: "/api-keys",
  getParentRoute: () => DashboardRoute,
} as any);
const DashboardAuditRoute = DashboardAuditRouteImport.update({
  id: "/audit",
  path: "/audit",
  getParentRoute: () => DashboardRoute,
} as any);
const DashboardChatRoute = DashboardChatRouteImport.update({
  id: "/chat",
  path: "/chat",
  getParentRoute: () => DashboardRoute,
} as any);
const DashboardConnectorsRoute = DashboardConnectorsRouteImport.update({
  id: "/connectors",
  path: "/connectors",
  getParentRoute: () => DashboardRoute,
} as any);
const DashboardEvalsRoute = DashboardEvalsRouteImport.update({
  id: "/evals",
  path: "/evals",
  getParentRoute: () => DashboardRoute,
} as any);
const DashboardMcpRoute = DashboardMcpRouteImport.update({
  id: "/mcp",
  path: "/mcp",
  getParentRoute: () => DashboardRoute,
} as any);
const DashboardModelsRoute = DashboardModelsRouteImport.update({
  id: "/models",
  path: "/models",
  getParentRoute: () => DashboardRoute,
} as any);
const DashboardOverviewRoute = DashboardOverviewRouteImport.update({
  id: "/overview",
  path: "/overview",
  getParentRoute: () => DashboardRoute,
} as any);
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => DashboardRoute,
} as any);
const DashboardUsageRoute = DashboardUsageRouteImport.update({
  id: "/usage",
  path: "/usage",
  getParentRoute: () => DashboardRoute,
} as any);
const DashboardWebhooksRoute = DashboardWebhooksRouteImport.update({
  id: "/webhooks",
  path: "/webhooks",
  getParentRoute: () => DashboardRoute,
} as any);
const DashboardCollectionsIndexRoute =
  DashboardCollectionsIndexRouteImport.update({
    id: "/collections/",
    path: "/collections/",
    getParentRoute: () => DashboardRoute,
  } as any);
const DashboardCollectionsNameRoute =
  DashboardCollectionsNameRouteImport.update({
    id: "/collections/$name",
    path: "/collections/$name",
    getParentRoute: () => DashboardRoute,
  } as any);
const DashboardCollectionsNameIndexRoute =
  DashboardCollectionsNameIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => DashboardCollectionsNameRoute,
  } as any);
const DashboardCollectionsNameConnectorsRoute =
  DashboardCollectionsNameConnectorsRouteImport.update({
    id: "/connectors",
    path: "/connectors",
    getParentRoute: () => DashboardCollectionsNameRoute,
  } as any);
const DashboardCollectionsNameSearchRoute =
  DashboardCollectionsNameSearchRouteImport.update({
    id: "/search",
    path: "/search",
    getParentRoute: () => DashboardCollectionsNameRoute,
  } as any);
const DashboardCollectionsNameSettingsRoute =
  DashboardCollectionsNameSettingsRouteImport.update({
    id: "/settings",
    path: "/settings",
    getParentRoute: () => DashboardCollectionsNameRoute,
  } as any);
const DashboardCollectionsNameConnectorsIndexRoute =
  DashboardCollectionsNameConnectorsIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => DashboardCollectionsNameConnectorsRoute,
  } as any);
const DashboardCollectionsNameConnectorsS3Route =
  DashboardCollectionsNameConnectorsS3RouteImport.update({
    id: "/s3",
    path: "/s3",
    getParentRoute: () => DashboardCollectionsNameConnectorsRoute,
  } as any);
const DashboardCollectionsNameDocumentsIndexRoute =
  DashboardCollectionsNameDocumentsIndexRouteImport.update({
    id: "/documents/",
    path: "/documents/",
    getParentRoute: () => DashboardCollectionsNameRoute,
  } as any);
const DashboardCollectionsNameDocumentsDocIdRoute =
  DashboardCollectionsNameDocumentsDocIdRouteImport.update({
    id: "/documents/$docId",
    path: "/documents/$docId",
    getParentRoute: () => DashboardCollectionsNameRoute,
  } as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/onboarding": typeof OnboardingRoute;
  "/login": typeof AuthLoginRoute;
  "/setup": typeof AuthSetupRoute;
  "/access-logs": typeof DashboardAccessLogsRoute;
  "/api-keys": typeof DashboardApiKeysRoute;
  "/audit": typeof DashboardAuditRoute;
  "/chat": typeof DashboardChatRoute;
  "/connectors": typeof DashboardConnectorsRoute;
  "/evals": typeof DashboardEvalsRoute;
  "/mcp": typeof DashboardMcpRoute;
  "/models": typeof DashboardModelsRoute;
  "/overview": typeof DashboardOverviewRoute;
  "/settings": typeof DashboardSettingsRoute;
  "/usage": typeof DashboardUsageRoute;
  "/webhooks": typeof DashboardWebhooksRoute;
  "/collections/$name": typeof DashboardCollectionsNameRouteWithChildren;
  "/collections/": typeof DashboardCollectionsIndexRoute;
  "/collections/$name/connectors": typeof DashboardCollectionsNameConnectorsRouteWithChildren;
  "/collections/$name/search": typeof DashboardCollectionsNameSearchRoute;
  "/collections/$name/settings": typeof DashboardCollectionsNameSettingsRoute;
  "/collections/$name/": typeof DashboardCollectionsNameIndexRoute;
  "/collections/$name/connectors/s3": typeof DashboardCollectionsNameConnectorsS3Route;
  "/collections/$name/documents/$docId": typeof DashboardCollectionsNameDocumentsDocIdRoute;
  "/collections/$name/connectors/": typeof DashboardCollectionsNameConnectorsIndexRoute;
  "/collections/$name/documents/": typeof DashboardCollectionsNameDocumentsIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/onboarding": typeof OnboardingRoute;
  "/login": typeof AuthLoginRoute;
  "/setup": typeof AuthSetupRoute;
  "/access-logs": typeof DashboardAccessLogsRoute;
  "/api-keys": typeof DashboardApiKeysRoute;
  "/audit": typeof DashboardAuditRoute;
  "/chat": typeof DashboardChatRoute;
  "/connectors": typeof DashboardConnectorsRoute;
  "/evals": typeof DashboardEvalsRoute;
  "/mcp": typeof DashboardMcpRoute;
  "/models": typeof DashboardModelsRoute;
  "/overview": typeof DashboardOverviewRoute;
  "/settings": typeof DashboardSettingsRoute;
  "/usage": typeof DashboardUsageRoute;
  "/webhooks": typeof DashboardWebhooksRoute;
  "/collections": typeof DashboardCollectionsIndexRoute;
  "/collections/$name/search": typeof DashboardCollectionsNameSearchRoute;
  "/collections/$name/settings": typeof DashboardCollectionsNameSettingsRoute;
  "/collections/$name": typeof DashboardCollectionsNameIndexRoute;
  "/collections/$name/connectors/s3": typeof DashboardCollectionsNameConnectorsS3Route;
  "/collections/$name/documents/$docId": typeof DashboardCollectionsNameDocumentsDocIdRoute;
  "/collections/$name/connectors": typeof DashboardCollectionsNameConnectorsIndexRoute;
  "/collections/$name/documents": typeof DashboardCollectionsNameDocumentsIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/_auth": typeof AuthRouteWithChildren;
  "/_dashboard": typeof DashboardRouteWithChildren;
  "/onboarding": typeof OnboardingRoute;
  "/_auth/login": typeof AuthLoginRoute;
  "/_auth/setup": typeof AuthSetupRoute;
  "/_dashboard/access-logs": typeof DashboardAccessLogsRoute;
  "/_dashboard/api-keys": typeof DashboardApiKeysRoute;
  "/_dashboard/audit": typeof DashboardAuditRoute;
  "/_dashboard/chat": typeof DashboardChatRoute;
  "/_dashboard/connectors": typeof DashboardConnectorsRoute;
  "/_dashboard/evals": typeof DashboardEvalsRoute;
  "/_dashboard/mcp": typeof DashboardMcpRoute;
  "/_dashboard/models": typeof DashboardModelsRoute;
  "/_dashboard/overview": typeof DashboardOverviewRoute;
  "/_dashboard/settings": typeof DashboardSettingsRoute;
  "/_dashboard/usage": typeof DashboardUsageRoute;
  "/_dashboard/webhooks": typeof DashboardWebhooksRoute;
  "/_dashboard/collections/$name": typeof DashboardCollectionsNameRouteWithChildren;
  "/_dashboard/collections/": typeof DashboardCollectionsIndexRoute;
  "/_dashboard/collections/$name/connectors": typeof DashboardCollectionsNameConnectorsRouteWithChildren;
  "/_dashboard/collections/$name/search": typeof DashboardCollectionsNameSearchRoute;
  "/_dashboard/collections/$name/settings": typeof DashboardCollectionsNameSettingsRoute;
  "/_dashboard/collections/$name/": typeof DashboardCollectionsNameIndexRoute;
  "/_dashboard/collections/$name/connectors/s3": typeof DashboardCollectionsNameConnectorsS3Route;
  "/_dashboard/collections/$name/documents/$docId": typeof DashboardCollectionsNameDocumentsDocIdRoute;
  "/_dashboard/collections/$name/connectors/": typeof DashboardCollectionsNameConnectorsIndexRoute;
  "/_dashboard/collections/$name/documents/": typeof DashboardCollectionsNameDocumentsIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/onboarding"
    | "/login"
    | "/setup"
    | "/access-logs"
    | "/api-keys"
    | "/audit"
    | "/chat"
    | "/connectors"
    | "/evals"
    | "/mcp"
    | "/models"
    | "/overview"
    | "/settings"
    | "/usage"
    | "/webhooks"
    | "/collections/$name"
    | "/collections/"
    | "/collections/$name/connectors"
    | "/collections/$name/search"
    | "/collections/$name/settings"
    | "/collections/$name/"
    | "/collections/$name/connectors/s3"
    | "/collections/$name/documents/$docId"
    | "/collections/$name/connectors/"
    | "/collections/$name/documents/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/onboarding"
    | "/login"
    | "/setup"
    | "/access-logs"
    | "/api-keys"
    | "/audit"
    | "/chat"
    | "/connectors"
    | "/evals"
    | "/mcp"
    | "/models"
    | "/overview"
    | "/settings"
    | "/usage"
    | "/webhooks"
    | "/collections"
    | "/collections/$name/search"
    | "/collections/$name/settings"
    | "/collections/$name"
    | "/collections/$name/connectors/s3"
    | "/collections/$name/documents/$docId"
    | "/collections/$name/connectors"
    | "/collections/$name/documents";
  id:
    | "__root__"
    | "/"
    | "/_auth"
    | "/_dashboard"
    | "/onboarding"
    | "/_auth/login"
    | "/_auth/setup"
    | "/_dashboard/access-logs"
    | "/_dashboard/api-keys"
    | "/_dashboard/audit"
    | "/_dashboard/chat"
    | "/_dashboard/connectors"
    | "/_dashboard/evals"
    | "/_dashboard/mcp"
    | "/_dashboard/models"
    | "/_dashboard/overview"
    | "/_dashboard/settings"
    | "/_dashboard/usage"
    | "/_dashboard/webhooks"
    | "/_dashboard/collections/$name"
    | "/_dashboard/collections/"
    | "/_dashboard/collections/$name/connectors"
    | "/_dashboard/collections/$name/search"
    | "/_dashboard/collections/$name/settings"
    | "/_dashboard/collections/$name/"
    | "/_dashboard/collections/$name/connectors/s3"
    | "/_dashboard/collections/$name/documents/$docId"
    | "/_dashboard/collections/$name/connectors/"
    | "/_dashboard/collections/$name/documents/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AuthRoute: typeof AuthRouteWithChildren;
  DashboardRoute: typeof DashboardRouteWithChildren;
  OnboardingRoute: typeof OnboardingRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_auth": {
      id: "/_auth";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof AuthRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_dashboard": {
      id: "/_dashboard";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof DashboardRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/onboarding": {
      id: "/onboarding";
      path: "/onboarding";
      fullPath: "/onboarding";
      preLoaderRoute: typeof OnboardingRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_auth/login": {
      id: "/_auth/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof AuthLoginRouteImport;
      parentRoute: typeof AuthRoute;
    };
    "/_auth/setup": {
      id: "/_auth/setup";
      path: "/setup";
      fullPath: "/setup";
      preLoaderRoute: typeof AuthSetupRouteImport;
      parentRoute: typeof AuthRoute;
    };
    "/_dashboard/access-logs": {
      id: "/_dashboard/access-logs";
      path: "/access-logs";
      fullPath: "/access-logs";
      preLoaderRoute: typeof DashboardAccessLogsRouteImport;
      parentRoute: typeof DashboardRoute;
    };
    "/_dashboard/api-keys": {
      id: "/_dashboard/api-keys";
      path: "/api-keys";
      fullPath: "/api-keys";
      preLoaderRoute: typeof DashboardApiKeysRouteImport;
      parentRoute: typeof DashboardRoute;
    };
    "/_dashboard/audit": {
      id: "/_dashboard/audit";
      path: "/audit";
      fullPath: "/audit";
      preLoaderRoute: typeof DashboardAuditRouteImport;
      parentRoute: typeof DashboardRoute;
    };
    "/_dashboard/chat": {
      id: "/_dashboard/chat";
      path: "/chat";
      fullPath: "/chat";
      preLoaderRoute: typeof DashboardChatRouteImport;
      parentRoute: typeof DashboardRoute;
    };
    "/_dashboard/connectors": {
      id: "/_dashboard/connectors";
      path: "/connectors";
      fullPath: "/connectors";
      preLoaderRoute: typeof DashboardConnectorsRouteImport;
      parentRoute: typeof DashboardRoute;
    };
    "/_dashboard/evals": {
      id: "/_dashboard/evals";
      path: "/evals";
      fullPath: "/evals";
      preLoaderRoute: typeof DashboardEvalsRouteImport;
      parentRoute: typeof DashboardRoute;
    };
    "/_dashboard/mcp": {
      id: "/_dashboard/mcp";
      path: "/mcp";
      fullPath: "/mcp";
      preLoaderRoute: typeof DashboardMcpRouteImport;
      parentRoute: typeof DashboardRoute;
    };
    "/_dashboard/models": {
      id: "/_dashboard/models";
      path: "/models";
      fullPath: "/models";
      preLoaderRoute: typeof DashboardModelsRouteImport;
      parentRoute: typeof DashboardRoute;
    };
    "/_dashboard/overview": {
      id: "/_dashboard/overview";
      path: "/overview";
      fullPath: "/overview";
      preLoaderRoute: typeof DashboardOverviewRouteImport;
      parentRoute: typeof DashboardRoute;
    };
    "/_dashboard/settings": {
      id: "/_dashboard/settings";
      path: "/settings";
      fullPath: "/settings";
      preLoaderRoute: typeof DashboardSettingsRouteImport;
      parentRoute: typeof DashboardRoute;
    };
    "/_dashboard/usage": {
      id: "/_dashboard/usage";
      path: "/usage";
      fullPath: "/usage";
      preLoaderRoute: typeof DashboardUsageRouteImport;
      parentRoute: typeof DashboardRoute;
    };
    "/_dashboard/webhooks": {
      id: "/_dashboard/webhooks";
      path: "/webhooks";
      fullPath: "/webhooks";
      preLoaderRoute: typeof DashboardWebhooksRouteImport;
      parentRoute: typeof DashboardRoute;
    };
    "/_dashboard/collections/": {
      id: "/_dashboard/collections/";
      path: "/collections";
      fullPath: "/collections/";
      preLoaderRoute: typeof DashboardCollectionsIndexRouteImport;
      parentRoute: typeof DashboardRoute;
    };
    "/_dashboard/collections/$name": {
      id: "/_dashboard/collections/$name";
      path: "/collections/$name";
      fullPath: "/collections/$name";
      preLoaderRoute: typeof DashboardCollectionsNameRouteImport;
      parentRoute: typeof DashboardRoute;
    };
    "/_dashboard/collections/$name/": {
      id: "/_dashboard/collections/$name/";
      path: "/";
      fullPath: "/collections/$name/";
      preLoaderRoute: typeof DashboardCollectionsNameIndexRouteImport;
      parentRoute: typeof DashboardCollectionsNameRoute;
    };
    "/_dashboard/collections/$name/connectors": {
      id: "/_dashboard/collections/$name/connectors";
      path: "/connectors";
      fullPath: "/collections/$name/connectors";
      preLoaderRoute: typeof DashboardCollectionsNameConnectorsRouteImport;
      parentRoute: typeof DashboardCollectionsNameRoute;
    };
    "/_dashboard/collections/$name/search": {
      id: "/_dashboard/collections/$name/search";
      path: "/search";
      fullPath: "/collections/$name/search";
      preLoaderRoute: typeof DashboardCollectionsNameSearchRouteImport;
      parentRoute: typeof DashboardCollectionsNameRoute;
    };
    "/_dashboard/collections/$name/settings": {
      id: "/_dashboard/collections/$name/settings";
      path: "/settings";
      fullPath: "/collections/$name/settings";
      preLoaderRoute: typeof DashboardCollectionsNameSettingsRouteImport;
      parentRoute: typeof DashboardCollectionsNameRoute;
    };
    "/_dashboard/collections/$name/connectors/": {
      id: "/_dashboard/collections/$name/connectors/";
      path: "/";
      fullPath: "/collections/$name/connectors/";
      preLoaderRoute: typeof DashboardCollectionsNameConnectorsIndexRouteImport;
      parentRoute: typeof DashboardCollectionsNameConnectorsRoute;
    };
    "/_dashboard/collections/$name/connectors/s3": {
      id: "/_dashboard/collections/$name/connectors/s3";
      path: "/s3";
      fullPath: "/collections/$name/connectors/s3";
      preLoaderRoute: typeof DashboardCollectionsNameConnectorsS3RouteImport;
      parentRoute: typeof DashboardCollectionsNameConnectorsRoute;
    };
    "/_dashboard/collections/$name/documents/": {
      id: "/_dashboard/collections/$name/documents/";
      path: "/documents";
      fullPath: "/collections/$name/documents/";
      preLoaderRoute: typeof DashboardCollectionsNameDocumentsIndexRouteImport;
      parentRoute: typeof DashboardCollectionsNameRoute;
    };
    "/_dashboard/collections/$name/documents/$docId": {
      id: "/_dashboard/collections/$name/documents/$docId";
      path: "/documents/$docId";
      fullPath: "/collections/$name/documents/$docId";
      preLoaderRoute: typeof DashboardCollectionsNameDocumentsDocIdRouteImport;
      parentRoute: typeof DashboardCollectionsNameRoute;
    };
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute;
  AuthSetupRoute: typeof AuthSetupRoute;
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSetupRoute: AuthSetupRoute,
};

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren);

interface DashboardCollectionsNameConnectorsRouteChildren {
  DashboardCollectionsNameConnectorsS3Route: typeof DashboardCollectionsNameConnectorsS3Route;
  DashboardCollectionsNameConnectorsIndexRoute: typeof DashboardCollectionsNameConnectorsIndexRoute;
}

const DashboardCollectionsNameConnectorsRouteChildren: DashboardCollectionsNameConnectorsRouteChildren =
  {
    DashboardCollectionsNameConnectorsS3Route:
      DashboardCollectionsNameConnectorsS3Route,
    DashboardCollectionsNameConnectorsIndexRoute:
      DashboardCollectionsNameConnectorsIndexRoute,
  };

const DashboardCollectionsNameConnectorsRouteWithChildren =
  DashboardCollectionsNameConnectorsRoute._addFileChildren(
    DashboardCollectionsNameConnectorsRouteChildren,
  );

interface DashboardCollectionsNameRouteChildren {
  DashboardCollectionsNameConnectorsRoute: typeof DashboardCollectionsNameConnectorsRouteWithChildren;
  DashboardCollectionsNameSearchRoute: typeof DashboardCollectionsNameSearchRoute;
  DashboardCollectionsNameSettingsRoute: typeof DashboardCollectionsNameSettingsRoute;
  DashboardCollectionsNameIndexRoute: typeof DashboardCollectionsNameIndexRoute;
  DashboardCollectionsNameDocumentsDocIdRoute: typeof DashboardCollectionsNameDocumentsDocIdRoute;
  DashboardCollectionsNameDocumentsIndexRoute: typeof DashboardCollectionsNameDocumentsIndexRoute;
}

const DashboardCollectionsNameRouteChildren: DashboardCollectionsNameRouteChildren =
  {
    DashboardCollectionsNameConnectorsRoute:
      DashboardCollectionsNameConnectorsRouteWithChildren,
    DashboardCollectionsNameSearchRoute: DashboardCollectionsNameSearchRoute,
    DashboardCollectionsNameSettingsRoute:
      DashboardCollectionsNameSettingsRoute,
    DashboardCollectionsNameIndexRoute: DashboardCollectionsNameIndexRoute,
    DashboardCollectionsNameDocumentsDocIdRoute:
      DashboardCollectionsNameDocumentsDocIdRoute,
    DashboardCollectionsNameDocumentsIndexRoute:
      DashboardCollectionsNameDocumentsIndexRoute,
  };

const DashboardCollectionsNameRouteWithChildren =
  DashboardCollectionsNameRoute._addFileChildren(
    DashboardCollectionsNameRouteChildren,
  );

interface DashboardRouteChildren {
  DashboardAccessLogsRoute: typeof DashboardAccessLogsRoute;
  DashboardApiKeysRoute: typeof DashboardApiKeysRoute;
  DashboardAuditRoute: typeof DashboardAuditRoute;
  DashboardChatRoute: typeof DashboardChatRoute;
  DashboardConnectorsRoute: typeof DashboardConnectorsRoute;
  DashboardEvalsRoute: typeof DashboardEvalsRoute;
  DashboardMcpRoute: typeof DashboardMcpRoute;
  DashboardModelsRoute: typeof DashboardModelsRoute;
  DashboardOverviewRoute: typeof DashboardOverviewRoute;
  DashboardSettingsRoute: typeof DashboardSettingsRoute;
  DashboardUsageRoute: typeof DashboardUsageRoute;
  DashboardWebhooksRoute: typeof DashboardWebhooksRoute;
  DashboardCollectionsNameRoute: typeof DashboardCollectionsNameRouteWithChildren;
  DashboardCollectionsIndexRoute: typeof DashboardCollectionsIndexRoute;
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAccessLogsRoute: DashboardAccessLogsRoute,
  DashboardApiKeysRoute: DashboardApiKeysRoute,
  DashboardAuditRoute: DashboardAuditRoute,
  DashboardChatRoute: DashboardChatRoute,
  DashboardConnectorsRoute: DashboardConnectorsRoute,
  DashboardEvalsRoute: DashboardEvalsRoute,
  DashboardMcpRoute: DashboardMcpRoute,
  DashboardModelsRoute: DashboardModelsRoute,
  DashboardOverviewRoute: DashboardOverviewRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardUsageRoute: DashboardUsageRoute,
  DashboardWebhooksRoute: DashboardWebhooksRoute,
  DashboardCollectionsNameRoute: DashboardCollectionsNameRouteWithChildren,
  DashboardCollectionsIndexRoute: DashboardCollectionsIndexRoute,
};

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
